### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/quizzical#1]
We need to improve the README by adding a short description, install steps, screenshots, etc.

**Comment by lorenzo774** [comment]
I have opened a PR with the changes requested.

**Comment by Dharmik48** [comment]
I reviewed your PR @lorenzo774, and it looks good but I have suggested a change in it, can you have a look?

And thank you for contributing😄

**Comment by abhishinde24** [comment]
Can i work on it is this issue is still open?

**Comment by lorenzo774** [comment]
@abhishinde24 It's closed, you can work on this repo: 👉https://github.com/Dharmik48/meme-generator
I opened a new issue: https://github.com/Dharmik48/meme-generator/issues/14

**Comment by lorenzo774** [comment]
I think it's closed

**Comment by Dharmik48** [comment]
> Can i work on it is this issue is still open?

Yes, you can. You can add a `Contributing` section and a `Thanks to all Contributors` section.

You can refer [this README](https://github.com/EddieHubCommunity/good-first-issue-finder/blob/main/README.md) to get a better idea.

**Comment by Dharmik48** [comment]
Thanks a lot @lorenzo774 and @abhishinde24 for contributing to the project!

**Comment by Dharmik48** [comment]
Closed with #9
