### ISSUE TITLE
[FEAT] Add a number of questions selector.

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/quizzical#11]
On the same page as difficulty and category selector, add one more field to select the number of questions in the quiz

**Comment by LalitDhane** [comment]
Hi Dharmik I want to work on this issue , can you assign this to me

**Comment by Dharmik48** [comment]
Good to see you are interested in contributing!

I will assign you for this issuse🚀

**Comment by LalitDhane** [comment]
Hi Dharmik. I made some code changes for the issue. Please let me know what you think of the changes below.

## Before

![image](https://user-images.githubusercontent.com/52025848/183249552-e7d04bde-4461-47be-aa51-c9c63a3ff335.png)

## After

![image](https://user-images.githubusercontent.com/52025848/183249588-59b7163e-ed29-424f-b7c4-9a1d76a2a653.png)

**Comment by Dharmik48** [comment]
Yeah, this looks great! Can you try implementing it as a dropdown list instead of radio buttons?

**Comment by LalitDhane** [comment]
will do

**Comment by Dharmik48** [comment]
Hey @LalitDhane, what's the status of this issue?

**Comment by LalitDhane** [comment]
Hi, I have been busy with my work lately ☺️ I will complete it this weekend

**Comment by Dharmik48** [comment]
Yeah sure! No problem😊

**Comment by LalitDhane** [comment]
Hey @Dharmik48  I've raised PR let me know if you have any suggestions
