### ISSUE TITLE
[FEATURE] Add "Back" button in Questions page

### ISSUE THREAD

**Issue by kabilansakthivelu** [Dharmik48/quizzical#15]
### Description

In Questions page, adding "Back" button to navigate to the topics modal will provide users to change a topic for the next set. Currently user have to refresh even after completing the quiz for choosing a different topic in the next game.

### Screenshots

<img width="1378" alt="Screenshot 2022-08-13 at 10 49 37 PM" src="https://user-images.githubusercontent.com/88023922/184504326-b15efe81-8a06-4e8f-a14d-b23bf0ac3b67.png">
<img width="1363" alt="Screenshot 2022-08-13 at 10 49 59 PM" src="https://user-images.githubusercontent.com/88023922/184504338-7b5a77b2-fa2f-4cb3-ac4f-5359bed396de.png">

**Comment by Dharmik48** [comment]
That's a very good feature we can add to improve UX!

**Comment by kabilansakthivelu** [comment]
Hi @Dharmik48, Kindly review the PR #16 raised for this enhancement.

**Comment by Dharmik48** [comment]
> Hi @Dharmik48, Kindly review the PR #16 raised for this enhancement.

Yes I did add my review to the PR.
