### ISSUE TITLE
Text parsing error: Question contains Non-parsed Unicode Characters

### ISSUE THREAD

**Issue by sahil-jindal** [Dharmik48/quizzical#19]
### Description

On production and on preview deployment, Question and choices contain non-parsed unicode (html entity) text. These text reduce the readibilty of the question.

### Screenshots

![Screenshot 2022-08-22 051405](https://user-images.githubusercontent.com/41242773/185815974-829250dd-484b-4d72-88b1-1a844e6e32db.png)
![Screenshot 2022-08-22 051444](https://user-images.githubusercontent.com/41242773/185815983-e9e96187-ea7e-4dc7-a9ce-f87653b63b5c.png)

**Comment by Dharmik48** [comment]
Yes, that is a terrible experience for the users! Thanks for pointing it out.

Would you like to work on this issue?

**Comment by mati5kova** [comment]
> Would you like to work on this issue?

Hello, you can assign me but I'll have to use a library the get the job done. That means I'll have to modify and commit package.json and package-lock.json files. Is that ok?

**Comment by Dharmik48** [comment]
Alright! I will assign you @mati5kova. And yes you can install a new package for it.
