### ISSUE TITLE
Add new feature to select category of questions

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/quizzical#2]
Before starting the game, we can add a page to select what category of questions the player is interested to play.

**Comment by arcetros** [comment]
Might take up this issue if no one is implementing it currently, any guidelines for contributing or should I just fork and pull? @Dharmik48

**Comment by Dharmik48** [comment]
Thanks for showing your interest to work on this! I will assign this to you.

You can check the [CONTRIBUTING.md](https://github.com/Dharmik48/quizzical/main/CONTRIBUTING.md) for the guidelines and the [Open Trivia Database](https://opentdb.com/) for the categories.
