### ISSUE TITLE
[DOCS] Adding License 

### ISSUE THREAD

**Issue by krupalitrivedi** [Dharmik48/quizzical#21]
### Description

Hi! This is an amazing project, I really enjoyed seeing the overall concept and really appreciate the effort you have put behind it!

I would recommend for you to please add a License to the project as it defines the rights of the contributors as well as people who will be using it.

**Comment by Dharmik48** [comment]
That's a valid point @krupalitrivedi. I should have added one from the start!

Thanks a lot for the reminder 😊
