### ISSUE TITLE
[DOCS] Adding Code of Conduct 

### ISSUE THREAD

**Issue by krupalitrivedi** [Dharmik48/quizzical#22]
### Description

Hello! 

I would recommend for you to add a Code of Conduct. There is a ready-to-put pre-formatted file provided by GitHub.

Steps to add Code of Conduct:
1. Go to `repository`
2.  Look for `Insights`
3. Move to `community standards`
4. Select - `Contributor Covenant`
5. Give your contact information and read through Code_of_conduct
6. Make a `commit`
7. Open a `Pull Request`

Here is a link for [steps by GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project)

PS: This can be a good first issue

**Comment by Dharmik48** [comment]
Thanks for raising this issue @krupalitrivedi! I too think that it's necessary to add a Code of Conduct to the repo.
