### ISSUE TITLE
Add a difficulty selector

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/quizzical#3]
Before starting the quiz, we can show a page to select the difficulty of the questions.

**Comment by Praveen-0208** [comment]
Hey @Dharmik48.. i would like to contribute to this issue. Can you please assign this issue to me?

**Comment by Dharmik48** [comment]
Alright! I will assign it to you Praveen.

**Comment by Praveen-0208** [comment]
Should the difficulty level be a new page or added as buttons in the
welcome screen itself ?

**Comment by Dharmik48** [comment]
I think it should be after welcome screen and before the game so a new page. What do you think?

**Comment by Praveen-0208** [comment]
> I think it should be after welcome screen and before the game so a new page. What do you think?

I think we can go with a new page, since we have to add the category as well in the later part

Or, we can add these options in the welcome screen itself. That would work too

**Comment by Dharmik48** [comment]
Yeah lets go with a new page, we have @arcetros working on adding the categories.

We might have a merge conflict but we'll figure it out.

**Comment by Praveen-0208** [comment]
Okay Dharmik

**Comment by Dharmik48** [comment]
You can check out the [Open Trivia Database](https://opentdb.com/) API docs for information on how to change the difficulty of questions fetched.

**Comment by arcetros** [comment]
![image](https://user-images.githubusercontent.com/75669794/182038616-f433ba79-b13d-40cf-abf1-eae3cffbca71.png)

Hey @Praveen-0208 @Dharmik48, What do you think of this?

**Comment by Praveen-0208** [comment]
Hey Dharmik. Could u verify and merge @arcetros 's PR, so that i can add on to that..?

**Comment by Dharmik48** [comment]
Yup, I think it looks great!

**Comment by Praveen-0208** [comment]
Hey Dharmik. Pushed code for selector. Please review and merge PR

**Comment by Dharmik48** [comment]
I reviewed your code and merged the PR. 

Thanks for the contribution🚀
