### ISSUE TITLE
[BUG] Correct answers is incorrect

### ISSUE THREAD

**Issue by arcetros** [Dharmik48/quizzical#6]
Hello @Dharmik48, I just read the source code and I noticed that your logic [here](https://github.com/Dharmik48/quizzical/blob/main/src/components/Question.jsxl) `setAnsIndex(randomIndex());` is used to set the correct answer randomly. I think this logic can make the confusion and unrest to the user.

I'm interested in contributing a fix for this issue, thanks ^-^

![image](https://user-images.githubusercontent.com/75669794/182102392-16e1f17e-74bf-43e3-9d9a-fa385ea7572a.png)

**Comment by Dharmik48** [comment]
Good of you to notice the bug @arcetros! I will assign this to you :)
