### ISSUE TITLE
fix: add a check if the user has selected answers for all questions

### ISSUE THREAD

**Issue by Dharmik48** [Dharmik48/quizzical#8]
As of now, a user can click on the `Check Answers` button without selecting answers for any question.

And if the user does this, then he gets all the answers right. We need to fix this ASAP

**Comment by faiz-ali-khan-developer** [comment]
Hey can you assign me this issue ???

**Comment by Dharmik48** [comment]
Sure!

**Comment by kabilansakthivelu** [comment]
Hi @Dharmik48, if this issue is open, could you please assign this to me?
